# Generated by Django 5.2.14 on 2026-08-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_fix_program_type_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='is_nep_2020',
            field=models.BooleanField(default=False, verbose_name='Is NEP-2020 Syllabus'),
        ),
    ]
