# Generated by Django 5.2.14 on 2026-08-20 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_syllabus_is_nep_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='external_links_heading',
            field=models.CharField(blank=True, default='Other External Links', help_text='Heading for the external links section on the department page', max_length=200),
        ),
        migrations.CreateModel(
            name='DepartmentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(verbose_name='URL')),
                ('image', models.ImageField(blank=True, help_text='Upload a cover image for this link card. If left blank, the website favicon will be resolved.', null=True, upload_to='dept/links/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='academics.department')),
            ],
            options={
                'verbose_name': 'Department Link',
                'verbose_name_plural': 'Department Links',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
