# Generated by Django 5.2.14 on 2026-08-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_remove_gallerycategory_gallery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='highlight_subtitle',
            field=models.CharField(blank=True, help_text='Optional subtitle/caption details for the homepage highlight popup.', max_length=250, verbose_name='Highlight Subtitle'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='is_homepage_highlight',
            field=models.BooleanField(default=False, help_text='Check to display this gallery item in the homepage popup highlights section.', verbose_name='Is Homepage Highlight'),
        ),
    ]
