# Generated by Django 5.2.14 on 2026-08-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_nonteaching_staff_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_highlights_heading',
            field=models.CharField(blank=True, default='Highlights', help_text="Custom heading for the highlights section inside the popup modal (defaults to 'Highlights')", max_length=200),
        ),
    ]
