# Generated by Django 5.0 on 2026-08-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_sitesettings_homepage_highlights_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='happening',
            name='highlight_subtitle',
            field=models.CharField(blank=True, help_text='Optional subtitle for the homepage highlight popup (defaults to category if empty).', max_length=250, verbose_name='Highlight Subtitle'),
        ),
        migrations.AddField(
            model_name='happening',
            name='is_homepage_highlight',
            field=models.BooleanField(default=False, help_text='Check to display this happening in the homepage popup highlights section.', verbose_name='Is Homepage Highlight'),
        ),
    ]
