# Generated by Django 5.0 on 2026-09-30 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_studentenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='board_grad',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='class_grad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='grade_grad',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='obtained_grad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='percentage_grad',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='stream12',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='stream_grad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='total_marks_grad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='year_grad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
