# Generated by Django 5.0 on 2026-10-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0007_studentenrollment_board_grad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='fee_amount',
            field=models.CharField(blank=True, default='500', max_length=20),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='uploads/enrollment_receipts/'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='payment_receipt_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='payment_status',
            field=models.CharField(blank=True, default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
