# Generated by Django 5.0 on 2026-10-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_studentenrollment_fee_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_title', models.CharField(default='चैतन्य साइंस एंड आर्ट्स कॉलेज, पामगढ़', help_text='Header college name', max_length=255)),
                ('title', models.CharField(default='छात्र नामांकन (Enrollment) प्रक्रिया — चरण-दर-चरण निर्देश', help_text='Process title / heading', max_length=255)),
                ('content_html', models.TextField(help_text='Rich HTML / text content of the enrollment instructions shown in the modal popup.')),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable the popup window on student dashboard.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enrollment Dashboard Instruction',
                'verbose_name_plural': 'Enrollment Dashboard Instructions',
            },
        ),
    ]
