# Generated by Django 5.0 on 2026-10-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0011_update_enrollment_instructions_styling'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='admin_remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
