# Generated by Django 5.0 on 2026-10-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0014_nepugadmissionenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='nepugadmissionenrollment',
            name='previous_board',
            field=models.CharField(blank=True, default='Shaheed Nandkumar Patel Vishwavidyalaya, Raigarh', help_text='Previous Board/University', max_length=150),
        ),
        migrations.AddField(
            model_name='nepugadmissionenrollment',
            name='previous_exam_name',
            field=models.CharField(blank=True, help_text='Previous Exam / Semester (e.g., B.A. Sem I)', max_length=100),
        ),
        migrations.AddField(
            model_name='nepugadmissionenrollment',
            name='previous_obtained_marks',
            field=models.CharField(blank=True, help_text='Previous semester marks obtained', max_length=50),
        ),
        migrations.AddField(
            model_name='nepugadmissionenrollment',
            name='previous_percentage',
            field=models.CharField(blank=True, help_text='Previous semester percentage or SGPA', max_length=20),
        ),
        migrations.AddField(
            model_name='nepugadmissionenrollment',
            name='previous_total_marks',
            field=models.CharField(blank=True, help_text='Previous semester total marks', max_length=50),
        ),
        migrations.AddField(
            model_name='nepugadmissionenrollment',
            name='previous_year',
            field=models.IntegerField(blank=True, help_text='Previous Exam Passing Year', null=True),
        ),
    ]
