# Generated by Django 5.0 on 2026-09-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_program_show_department_in_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='programcourse',
            name='course_code',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='programcourse',
            name='credit_l',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='programcourse',
            name='credit_p',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='programcourse',
            name='credit_t',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='programcourse',
            name='paper_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='programcourse',
            name='semester',
            field=models.CharField(blank=True, default='I', max_length=20),
        ),
    ]
